interface CountryCode {
  name: string;
  dial_code: string;
  code: string;
}

interface CountryGpsLocation {
  name: string;
  latitude: number;
  longitude: number;
  dial_code: string;
  code: string;
}

export const countryCodes: CountryCode[] = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    code: "AX",
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    code: "AS",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
  },
  {
    name: "Angola",
    dial_code: "+244",
    code: "AO",
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    code: "AI",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    code: "AQ",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    code: "AW",
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    code: "BS",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    code: "BB",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    code: "BY",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    code: "BE",
  },
  {
    name: "Belize",
    dial_code: "+501",
    code: "BZ",
  },
  {
    name: "Benin",
    dial_code: "+229",
    code: "BJ",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    code: "BM",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    code: "BT",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    code: "BW",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    code: "BG",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    code: "BI",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    code: "KH",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    code: "CM",
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    code: "CV",
  },
  {
    name: "Cayman Islands",
    dial_code: "+ 345",
    code: "KY",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
  },
  {
    name: "Chad",
    dial_code: "+235",
    code: "TD",
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    code: "CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    code: "KM",
  },
  {
    name: "Congo",
    dial_code: "+242",
    code: "CG",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    code: "CK",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    code: "HR",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    code: "CU",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    code: "CY",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    code: "DK",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    code: "DJ",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    code: "EC",
  },
  {
    name: "Egypt",
    dial_code: "+20",
    code: "EG",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    code: "ER",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    code: "EE",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    code: "ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    code: "FJ",
  },
  {
    name: "Finland",
    dial_code: "+358",
    code: "FI",
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    code: "GF",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    code: "GA",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    code: "GM",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    code: "GE",
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    code: "GH",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    code: "GI",
  },
  {
    name: "Greece",
    dial_code: "+30",
    code: "GR",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    code: "GL",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    code: "GD",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
  },
  {
    name: "Guam",
    dial_code: "+1671",
    code: "GU",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    code: "GT",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    code: "GG",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    code: "GN",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
  },
  {
    name: "Guyana",
    dial_code: "+595",
    code: "GY",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    code: "HT",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    code: "HN",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    code: "HK",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    code: "HU",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    code: "IS",
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    code: "ID",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    code: "IR",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    code: "IQ",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    code: "IE",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    code: "IM",
  },
  {
    name: "Israel",
    dial_code: "+972",
    code: "IL",
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    code: "JM",
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    code: "JE",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    code: "JO",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    code: "KZ",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    code: "KE",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    code: "KI",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    code: "KP",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    code: "KR",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    code: "KW",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
  },
  {
    name: "Laos",
    dial_code: "+856",
    code: "LA",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    code: "LV",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    code: "LB",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    code: "LS",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    code: "LR",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    code: "LT",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    code: "LU",
  },
  {
    name: "Macao",
    dial_code: "+853",
    code: "MO",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    code: "MK",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    code: "MG",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    code: "MW",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    code: "MY",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    code: "MV",
  },
  {
    name: "Mali",
    dial_code: "+223",
    code: "ML",
  },
  {
    name: "Malta",
    dial_code: "+356",
    code: "MT",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    code: "MH",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    code: "MQ",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    code: "MR",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    code: "MU",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    code: "YT",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    code: "FM",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    code: "MD",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    code: "MC",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    code: "MN",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    code: "ME",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    code: "MS",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    code: "MA",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    code: "MZ",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    code: "MM",
  },
  {
    name: "Namibia",
    dial_code: "+264",
    code: "NA",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    code: "NR",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    code: "NP",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    code: "NL",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    code: "AN",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    code: "NC",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    code: "NZ",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    code: "NI",
  },
  {
    name: "Niger",
    dial_code: "+227",
    code: "NE",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    code: "NG",
  },
  {
    name: "Niue",
    dial_code: "+683",
    code: "NU",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    code: "NF",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    code: "MP",
  },
  {
    name: "Norway",
    dial_code: "+47",
    code: "NO",
  },
  {
    name: "Oman",
    dial_code: "+968",
    code: "OM",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    code: "PK",
  },
  {
    name: "Palau",
    dial_code: "+680",
    code: "PW",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
  },
  {
    name: "Panama",
    dial_code: "+507",
    code: "PA",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    code: "PY",
  },
  {
    name: "Peru",
    dial_code: "+51",
    code: "PE",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    code: "PH",
  },
  {
    name: "Pitcairn",
    dial_code: "+872",
    code: "PN",
  },
  {
    name: "Poland",
    dial_code: "+48",
    code: "PL",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    code: "PT",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    code: "PR",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    code: "QA",
  },
  {
    name: "Romania",
    dial_code: "+40",
    code: "RO",
  },
  {
    name: "Russia",
    dial_code: "+7",
    code: "RU",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    code: "RW",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    code: "RE",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    code: "KN",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    code: "LC",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    code: "MF",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    code: "VC",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    code: "WS",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    code: "SM",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    code: "SA",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    code: "SN",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    code: "RS",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    code: "SC",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    code: "SL",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    code: "SG",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    code: "SK",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    code: "SI",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    code: "SB",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    code: "SO",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    code: "ZA",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    code: "SS",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    code: "GS",
  },
  {
    name: "Spain",
    dial_code: "+34",
    code: "ES",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    code: "LK",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    code: "SD",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    code: "SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    code: "SJ",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    code: "SZ",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    code: "SE",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    code: "CH",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    code: "TW",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    code: "TJ",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    code: "TZ",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    code: "TH",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    code: "TL",
  },
  {
    name: "Togo",
    dial_code: "+228",
    code: "TG",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    code: "TK",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    code: "TO",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    code: "TN",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    code: "TR",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    code: "TC",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    code: "TV",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    code: "UG",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    code: "UA",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    code: "VU",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    code: "VE",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    code: "VN",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    code: "VG",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    code: "VI",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    code: "YE",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    code: "ZM",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    code: "ZW",
  },
];

export const countryGpsLocation: CountryGpsLocation[] = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
    latitude: 33.93911,
    longitude: 67.709953,
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    code: "AX",
    latitude: 60.1785,
    longitude: 19.9156,
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
    latitude: 41.1533,
    longitude: 20.1683,
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
    latitude: 28.0339,
    longitude: 1.6596,
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    code: "AS",
    latitude: -14.270972,
    longitude: -170.132217,
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
    latitude: 42.5462,
    longitude: 1.6016,
  },
  {
    name: "Angola",
    dial_code: "+244",
    code: "AO",
    latitude: -11.2027,
    longitude: 17.8739,
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    code: "AI",
    latitude: 18.2206,
    longitude: -63.0686,
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    code: "AQ",
    latitude: -75.250973,
    longitude: -0.071389,
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
    latitude: 17.0608,
    longitude: -61.7964,
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
    latitude: -38.4161,
    longitude: -63.6167,
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
    latitude: 40.0691,
    longitude: 45.0382,
  },
  {
    name: "Aruba",
    dial_code: "+297",
    code: "AW",
    latitude: 12.5211,
    longitude: -69.9683,
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
    latitude: -25.2744,
    longitude: 133.7751,
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
    latitude: 47.5162,
    longitude: 14.5501,
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
    latitude: 40.1431,
    longitude: 47.5769,
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    code: "BS",
    latitude: 25.0343,
    longitude: -77.3963,
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
    latitude: 25.9304,
    longitude: 50.6378,
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
    latitude: 23.684994,
    longitude: 90.356331,
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    code: "BB",
    latitude: 13.1939,
    longitude: -59.5432,
  },
  {
    name: "Belarus",
    dial_code: "+375",
    code: "BY",
    latitude: 53.7098,
    longitude: 27.9534,
  },
  {
    name: "Belgium",
    dial_code: "+32",
    code: "BE",
    latitude: 50.5039,
    longitude: 4.4699,
  },
  {
    name: "Belize",
    dial_code: "+501",
    code: "BZ",
    latitude: 17.1899,
    longitude: -88.4976,
  },
  {
    name: "Benin",
    dial_code: "+229",
    code: "BJ",
    latitude: 9.3077,
    longitude: 2.3158,
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    code: "BM",
    latitude: 32.3214,
    longitude: -64.7574,
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    code: "BT",
    latitude: 27.5142,
    longitude: 90.4336,
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
    latitude: -16.2902,
    longitude: -63.5887,
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
    latitude: 43.9159,
    longitude: 17.6791,
  },
  {
    name: "Botswana",
    dial_code: "+267",
    code: "BW",
    latitude: -22.3285,
    longitude: 24.6849,
  },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
    latitude: -14.235,
    longitude: -51.9253,
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
    latitude: -6.3432,
    longitude: 71.8765,
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
    latitude: 4.5353,
    longitude: 114.728,
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    code: "BG",
    latitude: 42.7339,
    longitude: 25.4858,
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
    latitude: 12.2383,
    longitude: -1.5616,
  },
  {
    name: "Burundi",
    dial_code: "+257",
    code: "BI",
    latitude: -3.3731,
    longitude: 29.9189,
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    code: "KH",
    latitude: 12.5657,
    longitude: 104.991,
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    code: "CM",
    latitude: 7.3697,
    longitude: 12.3547,
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
    latitude: 56.1304,
    longitude: -106.3468,
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    code: "CV",
    latitude: 16.0021,
    longitude: -24.0132,
  },
  {
    name: "Cayman Islands",
    dial_code: "+ 345",
    code: "KY",
    latitude: 19.3133,
    longitude: -81.2546,
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
    latitude: 6.6111,
    longitude: 20.9394,
  },
  {
    name: "Chad",
    dial_code: "+235",
    code: "TD",
    latitude: 15.4542,
    longitude: 18.7322,
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
    latitude: -35.6751,
    longitude: -71.543,
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
    latitude: 35.8617,
    longitude: 104.1954,
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    code: "CX",
    latitude: -10.4475,
    longitude: 105.6904,
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
    latitude: -12.1642,
    longitude: 96.8709,
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
    latitude: 4.5709,
    longitude: -74.2973,
  },
  {
    name: "Comoros",
    dial_code: "+269",
    code: "KM",
    latitude: -11.875,
    longitude: 43.8722,
  },
  {
    name: "Congo",
    dial_code: "+242",
    code: "CG",
    latitude: -0.228,
    longitude: 15.8277,
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
    latitude: -4.0383,
    longitude: 21.7587,
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    code: "CK",
    latitude: -21.2367,
    longitude: -159.7777,
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
    latitude: 9.7489,
    longitude: -83.7534,
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
    latitude: 7.5399,
    longitude: -5.5471,
  },
  {
    name: "Croatia",
    dial_code: "+385",
    code: "HR",
    latitude: 45.1,
    longitude: 15.2,
  },
  {
    name: "Cuba",
    dial_code: "+53",
    code: "CU",
    latitude: 21.5218,
    longitude: -77.7812,
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    code: "CY",
    latitude: 35.1264,
    longitude: 33.4299,
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
    latitude: 49.8175,
    longitude: 15.473,
  },
  {
    name: "Denmark",
    dial_code: "+45",
    code: "DK",
    latitude: 56.2639,
    longitude: 9.5018,
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    code: "DJ",
    latitude: 11.8251,
    longitude: 42.5903,
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    code: "DM",
    latitude: 15.415,
    longitude: -61.371,
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
    latitude: 18.7357,
    longitude: -70.1627,
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    code: "EC",
    latitude: -1.8312,
    longitude: -78.1834,
  },
  {
    name: "Egypt",
    dial_code: "+20",
    code: "EG",
    latitude: 26.8206,
    longitude: 30.8025,
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
    latitude: 13.7942,
    longitude: -88.8965,
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
    latitude: 1.6508,
    longitude: 10.2679,
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    code: "ER",
    latitude: 15.1794,
    longitude: 39.7823,
  },
  {
    name: "Estonia",
    dial_code: "+372",
    code: "EE",
    latitude: 58.5953,
    longitude: 25.0136,
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    code: "ET",
    latitude: 9.145,
    longitude: 40.4897,
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
    latitude: -51.7963,
    longitude: -59.5236,
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
    latitude: 61.8926,
    longitude: -6.9118,
  },
  {
    name: "Fiji",
    dial_code: "+679",
    code: "FJ",
    latitude: -16.5782,
    longitude: 179.4144,
  },
  {
    name: "Finland",
    dial_code: "+358",
    code: "FI",
    latitude: 61.9241,
    longitude: 25.7482,
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
    latitude: 46.2276,
    longitude: 2.2137,
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    code: "GF",
    latitude: 3.9339,
    longitude: -53.1258,
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
    latitude: -17.6797,
    longitude: -149.4068,
  },
  {
    name: "Gabon",
    dial_code: "+241",
    code: "GA",
    latitude: -0.8037,
    longitude: 11.6094,
  },
  {
    name: "Gambia",
    dial_code: "+220",
    code: "GM",
    latitude: 13.4432,
    longitude: -15.3101,
  },
  {
    name: "Georgia",
    dial_code: "+995",
    code: "GE",
    latitude: 42.3154,
    longitude: 43.3569,
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
    latitude: 51.1657,
    longitude: 10.4515,
  },
  {
    name: "Ghana",
    dial_code: "+233",
    code: "GH",
    latitude: 7.9465,
    longitude: -1.0232,
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    code: "GI",
    latitude: 36.1377,
    longitude: -5.3454,
  },
  {
    name: "Greece",
    dial_code: "+30",
    code: "GR",
    latitude: 39.0742,
    longitude: 21.8243,
  },
  {
    name: "Greenland",
    dial_code: "+299",
    code: "GL",
    latitude: 71.7069,
    longitude: -42.6043,
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    code: "GD",
    latitude: 12.2628,
    longitude: -61.6042,
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
    latitude: 16.9959,
    longitude: -62.0676,
  },
  {
    name: "Guam",
    dial_code: "+1671",
    code: "GU",
    latitude: 13.4443,
    longitude: 144.7937,
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    code: "GT",
    latitude: 15.7835,
    longitude: -90.2308,
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    code: "GG",
    latitude: 49.4657,
    longitude: -2.5853,
  },
  {
    name: "Guinea",
    dial_code: "+224",
    code: "GN",
    latitude: 9.9456,
    longitude: -9.6966,
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
    latitude: 11.8037,
    longitude: -15.1804,
  },
  {
    name: "Guyana",
    dial_code: "+595",
    code: "GY",
    latitude: 4.8604,
    longitude: -58.9302,
  },
  {
    name: "Haiti",
    dial_code: "+509",
    code: "HT",
    latitude: 18.9712,
    longitude: -72.2852,
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
    latitude: 41.9029,
    longitude: 12.4534,
  },
  {
    name: "Honduras",
    dial_code: "+504",
    code: "HN",
    latitude: 15.2,
    longitude: -86.2419,
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    code: "HK",
    latitude: 22.3964,
    longitude: 114.1095,
  },
  {
    name: "Hungary",
    dial_code: "+36",
    code: "HU",
    latitude: 47.1625,
    longitude: 19.5033,
  },
  {
    name: "Iceland",
    dial_code: "+354",
    code: "IS",
    latitude: 64.9631,
    longitude: -19.0208,
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
    latitude: 20.5937,
    longitude: 78.9629,
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    code: "ID",
    latitude: -0.7893,
    longitude: 113.9213,
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    code: "IR",
    latitude: 32.4279,
    longitude: 53.688,
  },
  {
    name: "Iraq",
    dial_code: "+964",
    code: "IQ",
    latitude: 33.2232,
    longitude: 43.6793,
  },
  {
    name: "Ireland",
    dial_code: "+353",
    code: "IE",
    latitude: 53.4129,
    longitude: -8.2439,
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    code: "IM",
    latitude: 54.2361,
    longitude: -4.5481,
  },
  {
    name: "Israel",
    dial_code: "+972",
    code: "IL",
    latitude: 31.0461,
    longitude: 34.8516,
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
    latitude: 41.8719,
    longitude: 12.5674,
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    code: "JM",
    latitude: 18.1096,
    longitude: -77.2975,
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
    latitude: 36.2048,
    longitude: 138.2529,
  },
  {
    name: "Jersey",
    dial_code: "+44",
    code: "JE",
    latitude: 49.2144,
    longitude: -2.1313,
  },
  {
    name: "Jordan",
    dial_code: "+962",
    code: "JO",
    latitude: 30.5852,
    longitude: 36.2384,
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    code: "KZ",
    latitude: 48.0196,
    longitude: 66.9237,
  },
  {
    name: "Kenya",
    dial_code: "+254",
    code: "KE",
    latitude: -0.0236,
    longitude: 37.9062,
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    code: "KI",
    latitude: -3.3704,
    longitude: -168.734,
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    code: "KP",
    latitude: 40.3399,
    longitude: 127.51,
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    code: "KR",
    latitude: 35.9078,
    longitude: 127.7669,
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    code: "KW",
    latitude: 29.3117,
    longitude: 47.4818,
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
    latitude: 41.2044,
    longitude: 74.7661,
  },
  {
    name: "Laos",
    dial_code: "+856",
    code: "LA",
    latitude: 19.8563,
    longitude: 102.4955,
  },
  {
    name: "Latvia",
    dial_code: "+371",
    code: "LV",
    latitude: 56.8796,
    longitude: 24.6032,
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    code: "LB",
    latitude: 33.8547,
    longitude: 35.8623,
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    code: "LS",
    latitude: -29.61,
    longitude: 28.2336,
  },
  {
    name: "Liberia",
    dial_code: "+231",
    code: "LR",
    latitude: 6.4281,
    longitude: -9.4295,
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
    latitude: 26.3351,
    longitude: 17.2283,
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
    latitude: 47.166,
    longitude: 9.5554,
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    code: "LT",
    latitude: 55.1694,
    longitude: 23.8813,
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    code: "LU",
    latitude: 49.8153,
    longitude: 6.1296,
  },
  // ...continue for all countries in your file using this format
];
