export const licenseConstData = [
    {
        title: "Ownership and Intellectual Property",
        description: [
            "All content, software, features, and services provided through the Teez platform—including the AI voice assistant, chatbot interface, voice call handling systems, UI/UX design, logos, trademarks, and supporting documentation—are the intellectual property of Teez or its licensors. This includes any content generated by the AI or automated systems.",
            "You acknowledge that no ownership rights are transferred to you through the use of the Teez app, and all rights not expressly granted are reserved by Teez."
        ],
        isDashed: false,
    },
    {
        title: "User License",
        description: "Teez grants registered users and dealerships a limited, non-exclusive, non-transferable, revocable license to access and use the Teez platform and services in accordance with their selected subscription plan (Pro, Business, or Enterprise). This license is solely for business purposes related to car sales, customer support, and communication with potential buyers.",
    },
    {
        title: "Usage Restrictions",
        description: [
            "You may not:",
            "- Copy, modify, distribute, reverse-engineer, or create derivative works of any part of the Teez platform",
            "- Use the AI or system for unlawful, harmful, or misleading purposes",
            "- License, sublicense, resell, or commercially exploit any part of the platform to third parties",
            "- Circumvent usage limits set by your subscription plan (e.g., included voice minutes)",
            "Any violation of these terms may result in suspension or termination of your account and license."
        ],
        isDashed: false,
    },
    {
        title: "Third-Party Integrations",
        description: "Teez may integrate with third-party platforms such as Twilio, CRM tools, and payment processors. These tools may be governed by separate licensing agreements. Users are responsible for complying with the terms and conditions of those third-party services when enabled."
    },
    {
        title: "Termination",
        description: "Your license to use Teez is active for as long as you maintain a valid subscription and comply with the terms. We reserve the right to suspend or revoke your license at any time if we detect misuse, non-payment, or violations of our policies."
    },
    {
        title: "Feedback and Contributions",
        description: "If you submit suggestions, feedback, or other content to improve Teez, you grant us a perpetual, royalty-free, worldwide license to use, modify, and incorporate your input into our platform without any obligation to you."
    }
]